### ISSUE TITLE
Add contact form

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/comakingspace.github.io#14]
We should add a small contact form which people can use to drop an E-Mail.

@Narquadah developed a small backend script, which @emka offered to deploy.

**Comment by Narquadah** [comment]
@emka https://github.com/comakingspace/contact_server

**Comment by NitramLegov** [comment]
@emka @Narquadah did this ever make it to our server? :)

**Comment by emka** [comment]
No, I think the updated idea was to run it on the same server as the website.
Putting it on our server can be done if that is the goal, what do you prefer @Narquadah ?

**Comment by Narquadah** [comment]
Well we can run it on the vserver without any issues; however, we still need some smtp for delivery.

**Comment by NitramLegov** [comment]
We don´t have a vserver as an organization 🤔
If we put it on another vserver, I think we need to adjust the data privacy information. As far as I remember that´s why we agreed on putting it on the schokokeks server

**Comment by NitramLegov** [comment]
Contact form added, needs an update once we got the new URL.

**Comment by NitramLegov** [comment]
The contact form and the server work in general. However, since the action of the form points to a different URL, the user is being redirected to a new page which is nasty.

@Narquadah and I are discussion some possible solutions and will update this issue accordingly :)

**Comment by NitramLegov** [comment]
Done
