### ISSUE TITLE
Add Newsletter signup form

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/comakingspace.github.io#15]
We should check the possibility to enable users to signup to our newsletter from within our homepage (without having to point them to the mailinglist signup page, which is not fitting our design).

**Comment by LukasFreeze** [comment]
It's possible to subscribe by simply sending an eMail to comaking-news-join@lists.comaking.space - would that be an option? The message does not need any subject or content, but needs to look like it was sent from the address that the subscriber has entered...

**Comment by LukasFreeze** [comment]
Nevermind, this should be easier:

the signup form could send a message to comaking-news-request@lists.comaking.space with no subject and the only body content
> subscribe address=_entered Address_

It worked from my address that is also permitted to send messages to the list as well as a "random" one.

sources:
* http://www.list.org/mailman-member/node41.html
* https://mailman.nmsu.edu/commands.html
* and tested myself

**Comment by LukasFreeze** [comment]
Update: none of the above applies anymore!

The current signup link is found under https://06kzl.mjt.lu/wgt/06kzl/ul/form?c=f935acdd
