### ISSUE TITLE
Blog layout

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/comakingspace.github.io#2]
We should change the layout of blog posts into something similar as the erfurt makerspace has:
https://makerspace-erfurt.de/

A picture on the left, on the right side first the title, then the teaser.

**Comment by NitramLegov** [comment]
First draft done, however, we really need to work on the padding and margins (#1)

**Comment by LukasFreeze** [comment]
For me (Firefox), the images and the text overlap quite a bit although there would be plenty of screen space. The mobile version works a bit better (image above text) but is also more narrow than it needs to be.

Is that what you mean by "need to work on the padding and margins" or a different issue?

**Comment by NitramLegov** [comment]
I changed the layout to a grid layout and for me it looks fine now.

We can always furtherly tweak it, but it should be sufficient for the moment.
