### ISSUE TITLE
Team Layout

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/comakingspace.github.io#3]
On the team page, the different team members (including the supervisors) should appear in a 2 column layout.

On a device with a lower widht, they should appear below each other.

**Comment by NitramLegov** [comment]
Changed this to a grid layout as well - open: Add media queries to change the appearance on small screens

**Comment by LukasFreeze** [comment]
Can we increase the gaps between columns, please (e.g. twice as wide)? With the justified text (Blocksatz?), there are some large spaces in the texts that are nearly as big as the one between and it becomes hard to read:
![image](https://user-images.githubusercontent.com/19755883/112705616-fbc70300-8e9f-11eb-94fc-ba94a2dd887d.png)
