### ISSUE TITLE
Kalendertitel (Diskussion)

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/comakingspace.github.io#31]
Ich finde "Öffnungszeiten" klingt immer so verkaufsmäßig - wie wäre es stattdessen mit "Unsere Veranstaltungen" als Überschrift für den Sidebar-Kalender? Das würde auch die einmaligen Sachen besser einschließen :-)

**Comment by NitramLegov** [comment]
Ich habe das mal in "Events" umbenannt, da wir diesen Teil der Seite nicht Übersetzung und "Events" meiner Meinung nach sowohl auf der deutschen als auch auf der englischen Seite funktioniert.
