### ISSUE TITLE
resize photos

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/comakingspace.github.io#33]
Photos are loaded in full resolution even when not needed for the displayed size, correct?

I'd suggest we strongly downscale the team photos, they are building up noticeably slow at the moment and are many times larger than needed:

![grafik](https://user-images.githubusercontent.com/19755883/112912591-26ab9400-90f8-11eb-844f-d595641fddfe.png)

**Comment by NitramLegov** [comment]
Hmmm, here are the file sizes:
Lukas - 222kb
Patrick - 311 kb
Martin - 117 kb

Ciaran - 63 kb
Johannes - 145 kb
Keno - 368 kb
Kim - 886 kb
Mitja - 126 kb

I think we might be able to reduce some of the image sizes further down by cropping - but would not expect a super significant impact. @Narquadah what do you think? Is it worth the effort?

**Comment by beanobeano** [comment]
Wow! I have lost some weight. Kim you need to trim down a bit there. 
    On Saturday, June 19, 2021, 02:41:47 PM GMT+2, Martin ***@***.***> wrote:  
 
 


Hmmm, here are the file sizes:
Lukas - 222kb
Patrick - 311 kb
Martin - 117 kb

Ciaran - 63 kb
Johannes - 145 kb
Keno - 368 kb
Kim - 886 kb
Mitja - 126 kb

I think we might be able to reduce some of the image sizes further down by cropping - but would not expect a super significant impact. @Narquadah what do you think? Is it worth the effort?
