### ISSUE TITLE
Spam Spam Spam

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/comakingspace.github.io#34]
Seit die neue Website live ist erhalten wir alle 2-3 Tage eine Spam-Email über das Kontaktformular.

Das sollten wir versuchen zu verhindern. Da das Spamaufkommen aktuell eher gering ist will ich ungern mit Captchas oder JavaScript arbeiten.

@Narquadah was hältst du davon, ein verstecktes form element einzufügen, das die Nachricht server-seitig verwirft?
https://www.nfriedly.com/techblog/2009/11/how-to-build-a-spam-free-contact-forms-without-captchas/

Der Artikel ist von 2009, aber ein Versuch ist es denke ich Wert.

**Comment by LukasFreeze** [comment]
Mittlerweile eher 2-3 *pro Tag*, ich hab das Gefühl es werden immer mehr 😣

**Comment by Narquadah** [comment]
So hab das mal eingebaut. Mal sehen obs passt!

**Comment by NitramLegov** [comment]
Inzwischen kriegen wir weniger Spam, die Maßnahme scheint also etwas gebracht zu haben.

Leider kommt aber trotzdem immer mal wieder Spam durch. Ich fürchte also wir müssen noch ein wenig tiefer in die "Trickkiste" greifen :/

**Comment by LukasFreeze** [comment]
Habt ihr nochmal was gemacht? Es ist jetzt schon erstaunlich lange ruhig :-)

**Comment by Pakue95** [comment]
Kim hat letzt noch ein Update gepusht, dass nochmal was mit JS hinzugefügt hatte.

**Comment by LukasFreeze** [comment]
Cool, danke @Narquadah !

Ich hatte mal mitgeschrieben, um zu sehen ob der erste Versuch was bringen würde (entgegen des ersten Eindrucks wohl eher nicht), aber jetzt hab ich Hoffnung 😁 

![image](https://user-images.githubusercontent.com/19755883/118707489-e1affe00-b81a-11eb-991c-93b099ea12df.png)
