### ISSUE TITLE
Images on blog disappear with too large Title

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/comakingspace.github.io#37]
If the Title of a blog post is too long and thus cannot be wrapped, the teaser-image disappars on small screens.

This can be tested by changing the Text of a blog post to "CodeWeek@CoMakingSpace" And then shrinking the width of the window to less than 426px.

Can we get the teaser-image a minimum width?

**Comment by Pakue95** [comment]
5ed69c039dccf0cc6478674e7a5207b35d6eecf1 and 0df9ba548bd25eed0a03bdd060979f97b7b99faa should improve the image behavior.
