### ISSUE TITLE
calendar widget does not scroll

### ISSUE THREAD

**Issue by LukasFreeze** [comakingspace/comakingspace.github.io#38]
**The calendar widget is taller than my laptop screen in weeks with many events:**

![image](https://user-images.githubusercontent.com/19755883/140644783-6be63642-36ba-49b4-9ea6-516f09dfb275.png)

**It currently does not scroll along with the rest of the page, could we add that somehow?**

**To see the last entries, I had to scroll all the way down and got this pretty result ;-)**

![image](https://user-images.githubusercontent.com/19755883/140644834-f4e6736f-cbf9-435f-9879-b418fec399c2.png)

**(Microsoft Edge, Windows 10)**

**Comment by LukasFreeze** [comment]
update: same appearance in Firefox, taking the calendar "into the footer" when scrolling all the way down (second picture) happens also in less packed weeks.

A second minor bug is also visible in my screenshots: the date "Donnerstag 11. November 2021" is wider than the widget's width, maybe we can add another couple of pixels there?

**Comment by Pakue95** [comment]
Scrolls now, but is limited to 100vh. The injected calendar css makes it a little annoying to do a proper overflow scroll based on viewport.
