### ISSUE TITLE
Suppress the sidebar on mobile devices

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/comakingspace.github.io#4]
On devices with a low width, the sidebar should not appear.

Ideally, it should not get loaded, since loading it means calls to the google calendar api (and might affect performance)

**Comment by beanobeano** [comment]
I think it is probably not acceptable that some content is suppressed if it was determined to be useful enough to be made prominent in a sidebar. 
We discussed this at the first Marketing Meeting. My understanding was that the sidebar was not an issue on mobile devices for our implementation. However, if there is an issue on mobile devices then we should find an alternative "responsive" solution.

**Comment by NitramLegov** [comment]
closed since not necessary anymore
