### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/comakingspace.github.io#5]
We need to add multilanguage support.

From a user perspective, this should ideally mean that there are DE / EN Links in the navbar, which just lead to the same page in english. Leading to the same page in english could mean that it just navigates to /en/site-name.
If no english page is available (e.g. for blog posts), we could think about offering a link to the german page on the 404 page.

From a technical perspective, I would add the following:
Texts that are stored in one of the .yml files (navbar, managers, etc.) could get an additional "text_en" field.
Content pages might just need to be copied over with the same name, but _en as a suffix. We could possibly handle the /en/site-name linking with the permalink functionality.
However, there might be some smart plugin that does the work for us.

**Comment by beanobeano** [comment]
Maybe some useful info here:
https://www.klaasnotfound.com/2017/02/16/proper-multilingual-site-with-github-pages-and-jekyll/

**Comment by NitramLegov** [comment]
Unfortunately, according to the GitHub pages documentation, we can only use supported plugins:
https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages-and-jekyll#plugins

A list of supported plugins can be found here and does not include a translation plugin :(
https://pages.github.com/versions/

However, some smart person developed another approach which might work for us:
https://sylvaindurand.org/making-jekyll-multilingual/

**Comment by NitramLegov** [comment]
We do now have multilanguage support. All English pages are now stored in the "en" folder:
https://github.com/comakingspace/comakingspace.github.io/tree/master/en

The following pages still contain german content and need to be translated (or content needs to be created):

- [x] contact.md
- [x] impressum.md
- [x] index.md

**Comment by NitramLegov** [comment]
https://github.com/comakingspace/comakingspace.github.io/commit/3dc746e6210f3871eddf6cb101a35879136e3194 adds the outstanding translations.

The legal notice will be handled in #22 shortly before going live.
