### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/comakingspace.github.io#6]
We should activate and configure the seo plugin

**Comment by beanobeano** [comment]
When going live. We need to ensure a smooth transition to the new website.
 - We need to generate a sitemap and submit it to google.
 - We should map old pages to new equivalent ones where possible. Put  301 redirects so google can pick up on them during transition.
 - Request Google crawls the new website.
 - Double check Google Index has found all pages on the new website.
 - Check for Crawl Errors and fix them as they can impact search placement.

**Comment by NitramLegov** [comment]
The jekyll seo plugin allows us to put meta tags on all pages. Lars indicated today some tags that make sense, which he proposes to use. Once done with the content, we can add this to the website.

**Comment by NitramLegov** [comment]
With https://github.com/comakingspace/comakingspace.github.io/commit/bc9173a11e4f961a9b20450e54f4df2f692ad8b6 I have activated the SEO-Tags plugin in order to provide the corresponding HTML Tags. 

@LarsKumbier would you mind double checking them and checking, whether additional tags would make sense? That would be a great help!

The tasks @beanobeano provided of course all make sense!

**Comment by LarsKumbier** [comment]
Looks good to me. I'd suggest we add at least a [schedule](https://schema.org/Schedule) for the open hours (as soon as they are available again) and a [Location](https://schema.org/Place) for the address, along with geo-coordinates.

**Comment by NitramLegov** [comment]
For reference: We now have an autogenerated sitemap available at https://comakingspace.github.io/sitemap.xml

@LarsKumbier Thank you for your feedback. I like the idea of adding the open hours and the location to our page.

According to google (https://developers.google.com/search/docs/data-types/local-business), there is a schema LocalBusiness (https://schema.org/LocalBusiness) we should use for this. We would add this to the head of each of the pages, correct?

What do you think?

**Comment by LarsKumbier** [comment]
Good start with the sitemap. Currently, the different languages are mixed into the schema. Do we have the information, which page is in which language? If so, we should add this to the sitemap - search engines use this information. 

```
<?xml version=”1.0″ encoding=”UTF-8″?>
  <urlset xmlns=”http://www.sitemaps.org/schemas/sitemap/0.9″ xmlns:xhtml=”http://www.w3.org/1999/xhtml”>
    <url>
      <loc>https://comakingspace.github.io/neuigkeiten/</loc> <!-- a page of our website -->
      <xhtml:link rel=”alternate” hreflang=”de” href=”https://comakingspace.github.io/neuigkeiten/” /> <!-- the *same* link for the german representation -->
      <xhtml:link rel=”alternate” hreflang=”en” href=”https://comakingspace.github.io/news/” /> <!-- *another* link for the english representation -->
    </url>
...
```
Further Info: https://developers.google.com/search/docs/advanced/crawling/localized-versions?hl=en&visit_id=637513894161535442-3593284385&rd=2

As for the `Local Business` schema... I'm unsure. We're not primary a business, but a community - the legal business entity is for legal reasons, i.e. to restrict liability for the executive board. But I tend to agree in this case, because the [fitting micro schemas](https://schema.org/NonprofitType) do not contain the german variance of gGmbH and are not accepted as a standard yet - and I could not find any info from search engines for a better fitting accepted schema.

**Comment by NitramLegov** [comment]
I have replaced the SEO plugin by custom code, which now applies the meta tags to each page (https://github.com/comakingspace/comakingspace.github.io/blob/master/_includes/seo_general.html)

In addition, it adds the Website Schema to each page (https://github.com/comakingspace/comakingspace.github.io/blob/master/_includes/schemas/website.html)

In addition, it adds the LocalBusiness Schema to each page (https://github.com/comakingspace/comakingspace.github.io/blob/master/_includes/schemas/localBusiness.html)


@Narquadah is currently taking care of replacing the sitemap plugin by custom code in order to be able to provide alternative links for multilanguage pages.

**Comment by NitramLegov** [comment]
Thanks to @Narquadah we do now have a autogenerated sitemap which includes links to other languages (Whoop Whoop!)

Additionally, I have checked the lighthouse report and fixed a few minor issues to get all lights green :)

Mobile:
![image](https://user-images.githubusercontent.com/7809163/111923426-73132600-8a9f-11eb-979f-e09a2f30c41d.png)

Desktop:
![image](https://user-images.githubusercontent.com/7809163/111923438-845c3280-8a9f-11eb-88e7-e27f69b14d5f.png)

Regarding the structured data, I have used the rich result analysis tool of google (https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=url&url=https%3A%2F%2Fcomakingspace.github.io) to check the validity of our data.

It seems valid:
![image](https://user-images.githubusercontent.com/7809163/111923504-e321ac00-8a9f-11eb-8b96-4d23f5cb85a4.png)


@LarsKumbier would you mind another quick check/review?

Regarding the 301 redirects @beanobeano has mentioned, I have activated the jekyll-redirect-from plugin and added 301 redirects for all the old pages :)

**Comment by NitramLegov** [comment]
Done. For any further topics a new issue should be opened.
