### ISSUE TITLE
Add names, description and pictures for managers and supervisors

### ISSUE THREAD

**Issue by NitramLegov** [comakingspace/comakingspace.github.io#9]
The "Team" page needs some content. Doing this means:

* Get permission from all named people
* Get a picture from all these people
* Get a small introductionary sentence for all these people

**Comment by beanobeano** [comment]
Email requests sent.

**Comment by NitramLegov** [comment]
@beanobeano Quick Question: Do you by chance still have the answers of these E-Mails stored somewhere? Otherwise I´d just follow up with the folks :)

**Comment by beanobeano** [comment]
I think they were in the ciaran@comaking.space acct. Generally people just pointed to the blurb and photos on the wiki.
    On Wednesday, April 22, 2020, 07:31:18 PM GMT+2, NitramLegov <notifications@github.com> wrote:  
 
 


@beanobeano Quick Question: Do you by chance still have the answers of these E-Mails stored somewhere? Otherwise I´d just follow up with the folks :)

**Comment by NitramLegov** [comment]
Thank you. I´m going to assign everybody to provide the picture and description for the Website.

- [x] @NitramLegov 
- [x] @LukasFreeze 
- [x] @Pakue95 

- [x] @Narquadah 
- [x] @emka 
- [x] @kenomaerz 
- [x] @Johannes09 
- [x] @beanobeano 

Please post a short description of yourself and a picture (or a link to a picture) of yourself which can be added to our website. In case you do not want to be mentioned on the website, please indicate the same as well :) Please unassign yourself afterwards.

**Comment by LukasFreeze** [comment]
Hab die alte Mail gefunden und immer noch keine bessere Idee, also nehmen wir das :-P

> Feel free to take my wiki profile picture (https://wiki.comakingspace.de/File:Lukas_at_saw.jpg).
> 
> How long should the "background" text be? If just a short sentence, I'd say "Biologe mit besonderer Vorliebe für Holz, Upcycling und nachhaltigen Konsum."
> 
> If it should be a little longer, perhaps also add "Wenn er nicht gerade anderen Mitgliedern beim Einstieg hilft, experimentiert er im CoMakingSpace am liebsten mit individuellen Möbeln und selbstgebauten Werkzeugen."

**Comment by NitramLegov** [comment]
Ich habe auch mein Wiki Bild hinzugefügt und einen kleinen Text geschrieben.

Sneak peek, wie die Seite aussehen könnte: https://comakingspace.github.io/team/
Mir gefällts, Feedback gerne an @Narquadah und/oder mich :)

**Comment by kenomaerz** [comment]
Medizininformatiker und DJ. Baut eine Jukebox. Interessiert an Holzarbeit, Entwicklung am Raspberry Pi und CNC-Techniken. Sprich mit mir über Projektideen, neue Musik, gutes Essen und wie man den Space verbessern kann.

Kümmert sich um Space um Förderanträge und Spendenkampagnen. Hilfe und Ideen sind immer Willkommen.

**Comment by NitramLegov** [comment]
Von den meisten haben wir jetzt alles was wir brauchen :)

Es fehlt noch: 
- Die Beschreibung von @Pakue95 
- Das Bild von @Johannes09 
- Das Bild von @Narquadah 


Das sollte in den nächsten Tagen kommen, dann passt das hier :)

**Comment by NitramLegov** [comment]
This is done. Thanks to everybody!
